<?php
$products = array();
$products[1] = array('name'=>'Large Gas Grill', 'price' => 299.99, 'picture' => 'images/picture/grill1.jpg', 'checked' => '');
$products[2] = array('name'=>'Small Gas Grill', 'price' => 199.99, 'picture' => 'images/picture/grill2.jpg', 'checked' => '');
$products[3] = array('name'=>'Fire Pit', 'price' => 299.99, 'picture' => 'images/picture/firepit.jpg', 'checked' => '');
$products[4] = array('name'=>'Camp Pit', 'price' => 249.99, 'picture' => 'images/picture/camppit.jpg', 'checked' => '');
$products[5] = array('name'=>'Portable Grill', 'price' => 149.98, 'picture' => 'images/picture/portablegrill.jpg', 'checked' => '');
$products[6] = array('name'=>'Smoker', 'price' => 349.98, 'picture' => 'images/picture/smoker.jpg', 'checked' => '');
$products[7] = array('name'=>'Apron', 'price' => 7.99, 'picture' => 'images/picture/apron.jpg', 'checked' => '');
$products[8] = array('name'=>'BBQ Sauce', 'price' => 6.99, 'picture' => 'images/picture/sauce.jpg', 'checked' => '');
$products[9] = array('name'=>'Spatulas', 'price' => 24.99, 'picture' => 'images/picture/spatula.jpg', 'checked' => '');
$products[10] = array('name'=>'Fire Starters', 'price' => 9.99, 'picture' => 'images/picture/starters.jpg', 'checked' => '');
?>